{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "2a58faaa_e8bb2f7a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 5019
      },
      "writtenOn": "2023-05-19T15:31:17Z",
      "side": 1,
      "message": "I\u0027ve checked the failures of previous time this was landed - they look like use after free somewhere in c++ code. So I suspect there was some race during test destruction.\n\nI\u0027ve rerun bot that started failing then twice - it pass, so may be the root issue was fixed.",
      "revId": "4deec7ab29ab4816001aea57afdc0fa73b190429",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "737fd505_1aa1fa7c",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 6680
      },
      "writtenOn": "2023-05-19T15:39:50Z",
      "side": 1,
      "message": "LGTM",
      "revId": "4deec7ab29ab4816001aea57afdc0fa73b190429",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "1909d092_45ee0245",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 5366
      },
      "writtenOn": "2023-05-19T22:03:06Z",
      "side": 1,
      "message": "Did you find the reason why iOS tests were failing?",
      "revId": "4deec7ab29ab4816001aea57afdc0fa73b190429",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767"
    }
  ]
}