{
  "comments": [
    {
      "key": {
        "uuid": "f0dc610c_b2e54918",
        "filename": "modules/rtp_rtcp/source/forward_error_correction_internal.cc",
        "patchSetId": 16
      },
      "lineNbr": 17,
      "author": {
        "id": 5087
      },
      "writtenOn": "2018-04-03T15:12:47Z",
      "side": 1,
      "message": "This also seems unused (sorry for not catching this before).",
      "range": {
        "startLine": 17,
        "startChar": 0,
        "endLine": 17,
        "endChar": 31
      },
      "revId": "d1d49070bb307f2bfe08e3f1ae26f671bc698466",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767",
      "unresolved": true
    }
  ]
}